- name: Install packages for kvm
  become_user: root
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager

- name: Add user to the libvirt group
  become_user: root
  shell: sudo adduser {{ansible_user_id}} libvirt

- name: Add user to the kvm group
  become_user: root
  shell: sudo adduser {{ansible_user_id}} kvm

- name: enable libvirtd
  become_user: root
  shell: sudo systemctl enable --now libvirtd
